### ISSUE TITLE
Feature Request: Moderation

### ISSUE THREAD

**Issue by TheChessGuy2** [hyperbotauthor/listrawpoll#1]
Right now anyone can say anything on the site. I suggest moderation be implemented, so users can get banned and posts can be deleted.

**Comment by hyperbotauthor** [comment]
https://github.com/hyperbotauthor/listrawpoll/commit/dac57bdb909ba658adb85c1cf6ca2d7008ee8138

Introduced two kind of bans. One for users, and one for polls. Both can be imposed in an environment variable. The respective environment variables should hold space separated list of user ids or names / poll ids. Since this app runs on Heroku, the moderator interface is the Config vars session of Heroku dashboard, as this is the place where you can set environment variables for your app. In order to make moderation easier, the poll id will be shown next to the creation date.
